/* Generated By:JavaCC: Do not edit this line. usqlConstants.java */
package usql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface usqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 2;
  /** RegularExpression Id. */
  int DOUBLE = 3;
  /** RegularExpression Id. */
  int DATE = 4;
  /** RegularExpression Id. */
  int TEXT = 5;
  /** RegularExpression Id. */
  int BOOL = 6;
  /** RegularExpression Id. */
  int DATETIME = 7;
  /** RegularExpression Id. */
  int VERDADERO = 8;
  /** RegularExpression Id. */
  int FALSO = 9;
  /** RegularExpression Id. */
  int CREAR = 10;
  /** RegularExpression Id. */
  int BASE_DATOS = 11;
  /** RegularExpression Id. */
  int TABLA = 12;
  /** RegularExpression Id. */
  int OBJETO = 13;
  /** RegularExpression Id. */
  int PROCEDIMIENTO = 14;
  /** RegularExpression Id. */
  int FUNCION = 15;
  /** RegularExpression Id. */
  int USUARIO = 16;
  /** RegularExpression Id. */
  int COLOCAR = 17;
  /** RegularExpression Id. */
  int PASSWORD = 18;
  /** RegularExpression Id. */
  int NULO = 19;
  /** RegularExpression Id. */
  int NO_NULO = 20;
  /** RegularExpression Id. */
  int AUTOINCREMENTABLE = 21;
  /** RegularExpression Id. */
  int LLAVE_PRIMARIA = 22;
  /** RegularExpression Id. */
  int LLAVE_FORANEA = 23;
  /** RegularExpression Id. */
  int REFERENCIA = 24;
  /** RegularExpression Id. */
  int UNICO = 25;
  /** RegularExpression Id. */
  int USAR = 26;
  /** RegularExpression Id. */
  int ALTERAR = 27;
  /** RegularExpression Id. */
  int CAMBIAR = 28;
  /** RegularExpression Id. */
  int AGREGAR = 29;
  /** RegularExpression Id. */
  int QUITAR = 30;
  /** RegularExpression Id. */
  int ELIMINAR = 31;
  /** RegularExpression Id. */
  int BACKUP = 32;
  /** RegularExpression Id. */
  int RESTAURAR = 33;
  /** RegularExpression Id. */
  int USQLDUMP = 34;
  /** RegularExpression Id. */
  int COMPLETO = 35;
  /** RegularExpression Id. */
  int RETORNO = 36;
  /** RegularExpression Id. */
  int INSERTAR = 37;
  /** RegularExpression Id. */
  int EN = 38;
  /** RegularExpression Id. */
  int VALORES = 39;
  /** RegularExpression Id. */
  int DONDE = 40;
  /** RegularExpression Id. */
  int ACTUALIZAR = 41;
  /** RegularExpression Id. */
  int BORRAR = 42;
  /** RegularExpression Id. */
  int ORDENAR_POR = 43;
  /** RegularExpression Id. */
  int SELECCIONAR = 44;
  /** RegularExpression Id. */
  int DE = 45;
  /** RegularExpression Id. */
  int ASC = 46;
  /** RegularExpression Id. */
  int DESC = 47;
  /** RegularExpression Id. */
  int OTORGAR = 48;
  /** RegularExpression Id. */
  int DENEGAR = 49;
  /** RegularExpression Id. */
  int PERMISOS = 50;
  /** RegularExpression Id. */
  int DECLARAR = 51;
  /** RegularExpression Id. */
  int SI = 52;
  /** RegularExpression Id. */
  int SINO = 53;
  /** RegularExpression Id. */
  int SELECCIONA = 54;
  /** RegularExpression Id. */
  int CASO = 55;
  /** RegularExpression Id. */
  int DEFECTO = 56;
  /** RegularExpression Id. */
  int PARA = 57;
  /** RegularExpression Id. */
  int MIENTRAS = 58;
  /** RegularExpression Id. */
  int DETENER = 59;
  /** RegularExpression Id. */
  int IMPRIMIR = 60;
  /** RegularExpression Id. */
  int FECHA = 61;
  /** RegularExpression Id. */
  int FECHA_HORA = 62;
  /** RegularExpression Id. */
  int CONTAR = 63;
  /** RegularExpression Id. */
  int MAS = 64;
  /** RegularExpression Id. */
  int MENOS = 65;
  /** RegularExpression Id. */
  int POR = 66;
  /** RegularExpression Id. */
  int DIV = 67;
  /** RegularExpression Id. */
  int POT = 68;
  /** RegularExpression Id. */
  int MASMAS = 69;
  /** RegularExpression Id. */
  int MENOSMENOS = 70;
  /** RegularExpression Id. */
  int MENOR = 71;
  /** RegularExpression Id. */
  int MENORIGUAL = 72;
  /** RegularExpression Id. */
  int MAYOR = 73;
  /** RegularExpression Id. */
  int MAYORIGUAL = 74;
  /** RegularExpression Id. */
  int IGUALIGUAL = 75;
  /** RegularExpression Id. */
  int NOIGUAL = 76;
  /** RegularExpression Id. */
  int OR = 77;
  /** RegularExpression Id. */
  int AND = 78;
  /** RegularExpression Id. */
  int NOT = 79;
  /** RegularExpression Id. */
  int IGUAL = 80;
  /** RegularExpression Id. */
  int LLA1 = 81;
  /** RegularExpression Id. */
  int LLA2 = 82;
  /** RegularExpression Id. */
  int PAR1 = 83;
  /** RegularExpression Id. */
  int PAR2 = 84;
  /** RegularExpression Id. */
  int PUNTO = 85;
  /** RegularExpression Id. */
  int COMA = 86;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 87;
  /** RegularExpression Id. */
  int DOSPUNTOS = 88;
  /** RegularExpression Id. */
  int ASTERISCO = 89;
  /** RegularExpression Id. */
  int ID = 90;
  /** RegularExpression Id. */
  int NUMERO = 91;
  /** RegularExpression Id. */
  int CADENA = 92;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"INTEGER\"",
    "\"DOUBLE\"",
    "\"DATE\"",
    "\"TEXT\"",
    "\"BOOL\"",
    "\"DATETIME\"",
    "\"VERDADERO\"",
    "\"FALSO\"",
    "\"CREAR\"",
    "\"BASE_DATOS\"",
    "\"TABLA\"",
    "\"OBJETO\"",
    "\"PROCEDIMIENTO\"",
    "\"FUNCION\"",
    "\"USUARIO\"",
    "\"COLOCAR\"",
    "\"PASSWORD\"",
    "\"NULO\"",
    "\"NO_NULO\"",
    "\"AUTOINCREMENTABLE\"",
    "\"LLAVE_PRIMARIA\"",
    "\"LLAVE_FORANEA\"",
    "\"REFERENCIA\"",
    "\"UNICO\"",
    "\"USAR\"",
    "\"ALTERAR\"",
    "\"CAMBIAR\"",
    "\"AGREGAR\"",
    "\"QUITAR\"",
    "\"ELIMINAR\"",
    "\"BACKUP\"",
    "\"RESTAURAR\"",
    "\"USQLDUMP\"",
    "\"COMPLETO\"",
    "\"RETORNO\"",
    "\"INSERTAR\"",
    "\"EN\"",
    "\"VALORES\"",
    "\"DONDE\"",
    "\"ACTUALIZAR\"",
    "\"BORRAR\"",
    "\"ORDENAR_POR\"",
    "\"SELECCIONAR\"",
    "\"DE\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"OTORGAR\"",
    "\"DENEGAR\"",
    "\"PERMISOS\"",
    "\"DECLARAR\"",
    "\"SI\"",
    "\"SINO\"",
    "\"SELECCIONA\"",
    "\"CASO\"",
    "\"DEFECTO\"",
    "\"PARA\"",
    "\"MIENTRAS\"",
    "\"DETENER\"",
    "\"IMPRIMIR\"",
    "\"FECHA\"",
    "\"FECHA_HORA\"",
    "\"CONTAR\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"%\"",
    "<ID>",
    "<NUMERO>",
    "<CADENA>",
  };

}
