
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 21 07:42:47 CST 2017
//----------------------------------------------------

package servidorweb;

/** CUP generated class containing symbol constants. */
public class symU {
  /* terminals */
  public static final int ELIMINAR = 30;
  public static final int BOOL = 6;
  public static final int DEFECTO = 56;
  public static final int CONTAR = 63;
  public static final int BORRAR = 41;
  public static final int COLOCAR = 51;
  public static final int OTORGAR = 47;
  public static final int NO_NULO = 19;
  public static final int ORDENAR_POR = 42;
  public static final int TABLA = 12;
  public static final int VERDADERO = 8;
  public static final int ASC = 45;
  public static final int MAYOR = 71;
  public static final int SI = 52;
  public static final int CAMBIAR = 27;
  public static final int POT = 68;
  public static final int FALSO = 9;
  public static final int PASSWORD = 17;
  public static final int POR = 66;
  public static final int NUMERO = 90;
  public static final int INTEGER = 2;
  public static final int DOUBLE = 3;
  public static final int FUNCION = 15;
  public static final int DATETIME = 7;
  public static final int NOT = 79;
  public static final int BACKUP = 31;
  public static final int IGUALIGUAL = 80;
  public static final int TEXT = 5;
  public static final int VALORES = 38;
  public static final int RESTAURAR = 32;
  public static final int USQLDUMP = 33;
  public static final int PERMISOS = 49;
  public static final int CREAR = 10;
  public static final int EN = 37;
  public static final int DONDE = 39;
  public static final int PARA = 57;
  public static final int COMA = 86;
  public static final int UNICO = 24;
  public static final int PAR2 = 81;
  public static final int IGUAL = 75;
  public static final int FECHA = 61;
  public static final int PAR1 = 82;
  public static final int DETENER = 59;
  public static final int DENEGAR = 48;
  public static final int MASMAS = 69;
  public static final int AUTOINCREMENTABLE = 20;
  public static final int DOSPUNTOS = 88;
  public static final int SELECCIONAR = 43;
  public static final int PUNTOYCOMA = 87;
  public static final int ASTERISCO = 92;
  public static final int IMPRIMIR = 60;
  public static final int DIV = 67;
  public static final int OBJETO = 13;
  public static final int MENOS = 65;
  public static final int MENOR = 72;
  public static final int LLAVE_FORANEA = 22;
  public static final int MAS = 64;
  public static final int BASE_DATOS = 11;
  public static final int DE = 44;
  public static final int USUARIO = 16;
  public static final int NULO = 18;
  public static final int USAR = 25;
  public static final int EOF = 0;
  public static final int MIENTRAS = 58;
  public static final int PUNTO = 85;
  public static final int INSERTAR = 36;
  public static final int REFERENCIA = 23;
  public static final int SELECCIONA = 54;
  public static final int AGREGAR = 28;
  public static final int MENORIGUAL = 74;
  public static final int DECLARAR = 50;
  public static final int ALTERAR = 26;
  public static final int DATE = 4;
  public static final int OR = 77;
  public static final int error = 1;
  public static final int RETORNO = 35;
  public static final int LLA2 = 84;
  public static final int DESC = 46;
  public static final int ID = 89;
  public static final int LLA1 = 83;
  public static final int FECHA_HORA = 62;
  public static final int ACTUALIZAR = 40;
  public static final int SINO = 53;
  public static final int CASO = 55;
  public static final int COMPLETO = 34;
  public static final int NOIGUAL = 76;
  public static final int QUITAR = 29;
  public static final int CADENA = 91;
  public static final int MAYORIGUAL = 73;
  public static final int PROCEDIMIENTO = 14;
  public static final int AND = 78;
  public static final int MENOSMENOS = 70;
  public static final int LLAVE_PRIMARIA = 21;
}

